update _v

diff --git a/bin/_v b/bin/_v
--- a/bin/_v
+++ b/bin/_v
@@ -4,95 +4,225 @@
 #! Based on _v by Magnus Woldrich: https://github.com/trapd00r/utils/blob/master/_v
 
 : if 0
-  # Just pass through if not on a tty
-  if [ ! -t 1 ]; then
-    exec cat "${@}"
-  fi
-# try to find a better shell, especially on Solaris
 
-  PATH=/usr/local/bin:/opt/csw/bin:/opt/local/bin:/usr/dt/bin:/usr/xpg4/bin:/usr/bin:/bin:$PATH
+  _MY_SHELL=/bin/sh
+  export _MY_SHELL
 
   if [ -z "$IN_BASH" ] && command -v bash >/dev/null; then
     IN_BASH=1
     export IN_BASH
+    _MY_SHELL=`command -v bash`
+    export _MY_SHELL
     exec bash "$0" "$@"
   elif [ -z "$IN_BASH" ] && [ -z "$IN_KSH" ]; then
     if command -v dtksh >/dev/null; then
       IN_KSH=1
       export IN_KSH
+      _MY_SHELL=`command -v dtksh`
+      export _MY_SHELL
       exec dtksh "$0" "$@"
     elif [ -x /usr/xpg4/bin/sh ]; then
       IN_KSH=1
       export IN_KSH
+      _MY_SHELL=/usr/xpg4/bin/sh
+      export _MY_SHELL
       exec /usr/xpg4/bin/sh "$0" "$@"
     elif command -v ksh93 >/dev/null; then
       IN_KSH=1
       export IN_KSH
+      _MY_SHELL=`command -v ksh93`
+      export _MY_SHELL
       exec ksh93 "$0" "$@"
     elif command -v ksh >/dev/null; then
       IN_KSH=1
       export IN_KSH
+      _MY_SHELL=`command -v ksh`
+      export _MY_SHELL
       exec ksh "$0" "$@"
     else
-      echo "$0 requires either bash or ksh" >&2
-      exit
+      _MY_SHELL="${SHELL:-/bin/sh}"
     fi
   fi
 
-  # hopefully we're now POSIX
+  # hopefully we're now POSIX, and shell is saved in ${_MY_SHELL}
 
-  tmp_file=/tmp/vimcat_${$}
-  trap "rm -f ${tmp_file}" HUP INT QUIT ILL TRAP KILL BUS TERM
+  tmp_dir=/tmp
+  mkdir_options="-m 700"
 
-  script=$(command -v ${0})
+  case "$(uname -s)" in
+    MINGW*|MSYS*)
+      if [ -n "${temp}" ]; then
+        # MSYS2 is a little tricky, we're gonna stick to the user's private temp
+        # the -m mode switch to mkdir doesn't work
+        tmp_dir="$(cygpath --unix "${temp}")"
+        mkdir_options=""
+      fi
+    ;;
+  esac
+
+  tmp_dir="${tmp_dir}/vimcat_${$}"
+
+  if ! mkdir ${mkdir_options} "${tmp_dir}"; then
+    echo Could not create temporary directory "${tmp_dir}" >&2
+    exit 1
+  fi 
+
+  trap "rm -rf ${tmp_dir}" HUP INT QUIT ILL TRAP KILL BUS TERM
+  tmp_file_in="${tmp_dir}/vimcat_in.txt"
+  tmp_file_out="${tmp_dir}/vimcat_out.txt"
+
+  script="$(command -v ${0})"
 
   # check for arguments to pass to vim
-  while [ $# -gt 0 ] ; do
+  while [ "${#}" -gt 0 ] ; do
     case "${1}" in
-      "-c") shift; extra_c="${1}"; shift ;; 
-        -*) echo "bad option '${1}'" ; exit 1 ;;
-         *) break ;;
+      "-c")
+        shift
+        if [ -z "${extra_c}" ]; then
+          extra_c="${1}"
+        else
+          extra_c="${extra_c} | ${1}"
+        fi
+        shift
+        ;;
+      "--cmd")
+        shift
+        if [ -z "${extra_cmd}" ]; then
+          extra_cmd="${1}"
+        else
+          extra_cmd="${extra_cmd} | ${1}"
+        fi
+        shift
+        ;;
+      "-u")
+        shift
+        vimcatrc="${1}"
+        shift
+        ;;
+      "-o")
+        shift
+        output_file="${1}"
+        shift
+        ;;
+      "-s")
+        shift
+        squeeze_blank_lines=1
+        ;;
+      "--")
+        shift
+        break
+        ;;
+      -*)
+        echo "${0}: bad option '${1}'"
+        exit 1
+        ;;
+      *)
+        break
+        ;;
     esac
   done
 
-  files=("${@}")
-
-  if [ "${#}" -eq 0 ]; then
-    files[1]="-"
+  # Just pass through if not on a tty, unless -o was given
+  if [ -z "${output_file}" ]; then
+    if [ ! -t 1 ]; then
+      exec cat "${@}"
+    fi
   fi
 
-  for file in "${files[@]}"
+  if [ -z "${vimcatrc}" ]; then
+    if [ -f ~/.vimcatrc ]; then
+        vimcatrc="~/.vimcatrc"
+    else
+        vimcatrc=""
+    fi
+  fi
+
+  if [ -z "${extra_cmd}" ]; then
+    extra_cmd='silent! echo'
+  fi
+
+  if [ -z "${extra_c}" ]; then
+    extra_c='silent! echo'
+  fi
+
+  if [ "${#}" -eq 0 ]; then
+    set -- -
+  fi
+
+  for file in "$@"
   do
-    if [ "${#files[@]}" -ge 2 ]; then
-      echo "==> ${file} <=="
+    if [ "${#}" -ge 2 ]; then
+      echo
+      echo "${file}:" 
     fi
 
     if [ "${file}" = "-" ]; then
-      cat - >${tmp_file}
-      file=${tmp_file}
+      cat - >"${tmp_file_in}"
+      file="${tmp_file_in}"
+    fi
+
+    if [ "${squeeze_blank_lines}" = "1" ]; then
+      cat -- "${file}" > "${tmp_file_in}.work"
+      sed -e '/^[ 	]*$/{
+				N
+				/^[ 	]*\n[ 	]*$/D
+      }' -- "${tmp_file_in}.work" > "${tmp_file_in}"
+      rm -f -- "${tmp_file_in}.work"
+      file="${tmp_file_in}"
     fi
 
     # Check that the file exists
     if test -r "${file}" -a -f "${file}"; then
-      vim -E -X -R -i NONE -u /home/neg/.vim/vim_hi.rc -c "source ${script} | ${extra_c} | visual | call AnsiHighlight(\"${tmp_file}\") | q" "${file}" </dev/tty >/dev/null 2>&1
-      cat ${tmp_file}
-      echo
+      if test -s "${file}"; then
+        if [ -z "${output_file}" -o "${output_file}" = "-" ]; then
+          dest_file="${tmp_file_out}"
+        else
+          dest_file="${output_file}"
+        fi
+
+        if [ -n "${vimcatrc}" ]; then
+          vim -N -E -X -R -i NONE -u "${vimcatrc}" --cmd "visual | ${extra_cmd}" -c "set bg=dark | syn on | hi Normal ctermbg=NONE | silent! source ${script} | ${extra_c} | call AnsiHighlight(\"${dest_file}\") | q" -- "${file}" </dev/tty >/dev/null 2>&1
+        else
+          vim -N -E -X -R -i NONE                  --cmd "visual | ${extra_cmd}" -c "set bg=dark | syn on | hi Normal ctermbg=NONE | silent! source ${script} | ${extra_c} | call AnsiHighlight(\"${dest_file}\") | q" -- "${file}" </dev/tty >/dev/null 2>&1
+        fi
+
+        if [ -z "${output_file}" -o "${output_file}" = "-" ]; then
+          cat "${tmp_file_out}"
+        fi
+
+        if [ -z "${output_file}" ]; then
+          # if file doesn't end in a newline, output a newline
+          # regular Solaris tail does not work for this
+          tail_cmd=tail
+          if [ -x /usr/xpg4/bin/tail ]; then
+            tail_cmd=/usr/xpg4/bin/tail
+          fi
+          if command -v gtail >/dev/null; then
+            tail_cmd=gtail
+          fi
+          last_char="$($tail_cmd -c 1 "${tmp_file_out}")"
+          if [ "${last_char}" != "" ]; then
+            echo
+          fi
+        fi
+      fi
     else
-      echo "$0: Cannot read file: ${file}" >&2
+      echo "${0}: Cannot read file: ${file}" >&2
     fi
   done
 
-  rm -f "${tmp_file}"
+  rm -rf "${tmp_dir}"
 
   exit
 
-: endfor
+: endif
+: endif
+: endif
+: endif
+: endif
 : endwhile
 : endif
-: endif
-: endif
-: endif
-: endif
+: endfor
 
 " AnsiHighlight: Allows for marking up a file, using ANSI color escapes when
 " the syntax changes colors, for easy, faithful reproduction.
@@ -103,8 +233,7 @@
 " License: BSD. Completely open source, but I would like to be
 " credited if you use some of this code elsewhere.
 
-" Copyright (c) 2008, Matthew J. Wozniski {{{1
-" All rights reserved.
+" Copyright (c) 2015, Matthew J. Wozniski {{{1
 "
 " Redistribution and use in source and binary forms, with or without
 " modification, are permitted provided that the following conditions are met:
@@ -113,9 +242,6 @@
 " * Redistributions in binary form must reproduce the above copyright
 " notice, this list of conditions and the following disclaimer in the
 " documentation and/or other materials provided with the distribution.
-" * The names of the contributors may not be used to endorse or promote
-" products derived from this software without specific prior written
-" permission.
 "
 " THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER ``AS IS'' AND ANY
 " EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
@@ -179,7 +305,7 @@ function! s:GroupToAnsi(groupnum)
     unlet fg
   endif
 
-  if !exists('fg') && !groupnum == hlID('Normal')
+  if !exists('fg') && groupnum != hlID('Normal')
     let fg = synIDattr(hlID('Normal'), 'fg', s:type)
     if fg == "" || fg == -1
       unlet fg
@@ -240,18 +366,39 @@ function! AnsiHighlight(output_file)
         " Hopefully fix highlighting sync issues
     exe "norm! " . lnum . "G$"
 
-    let line = getline(lnum)
+    let line  = getline(lnum)
+    let cnum  = 1
 
-    for cnum in range(1, col('.'))
-      if synIDtrans(synID(lnum, cnum, 1)) != last
+    while cnum <=# col('.')
+      " skip ansi codes in the file
+      if cnum <=# col('.') - 1 && line[cnum-1] ==# "\e" && line[cnum] ==# '['
+        let cnum += 2
+        while match(line[cnum-1], '[A-Za-z]') ==# -1
+          let cnum += 1
+        endwhile
+
+        let cnum += 1
+        continue
+      endif
+
+      let concealed = synconcealed(lnum, cnum)
+
+      if concealed[0] !=# 1 && synIDtrans(synID(lnum, cnum, 1)) != last
         let last = synIDtrans(synID(lnum, cnum, 1))
         let output .= s:GroupToAnsi(last)
       endif
 
-      let output .= matchstr(line, '\%(\zs.\)\{'.cnum.'}')
+      if concealed[0] ==# 1 && &conceallevel !=# 0
+        if &conceallevel ==# 1 || &conceallevel ==# 2
+          let output .= concealed[1]
+        endif
+      else
+        let output .= line[cnum-1]
+      endif
       "let line = substitute(line, '.', '', '')
             "let line = matchstr(line, '^\@<!.*')
-    endfor
+      let cnum += 1
+    endwhile
     let retv += [output]
   endfor
   " Reset the colors to default after displaying the file
@@ -260,7 +407,8 @@ function! AnsiHighlight(output_file)
   return writefile(retv, a:output_file)
 endfunction
 
-" See copyright in the vimscript above.
+" See copyright in the vim script above (for the vim script) and in
+" vimcat.md for the whole script.
 "
 " The list of contributors is at the bottom of the vimpager script in this
 " project.
